-- HR verifies employment first; employer finance then verifies the authorised salary range.
ALTER TABLE applications DROP CONSTRAINT applications_status_check;
ALTER TABLE applications ADD CONSTRAINT applications_status_check CHECK (status IN (
  'DRAFT', 'SUBMITTED', 'BROKER_REVIEW', 'EMPLOYER_VERIFICATION',
  'EMPLOYER_FINANCE_VERIFICATION', 'LENDER_INITIAL_REVIEW', 'LENDER_FINAL_REVIEW',
  'CONTRACT_PENDING', 'CONTRACT_CONFIRMED', 'DISBURSEMENT_PENDING', 'DISBURSED',
  'REPAYMENT_ACTIVE', 'SETTLED', 'REJECTED', 'CLOSED'
));

ALTER TABLE approval_events DROP CONSTRAINT approval_events_stage_check;
ALTER TABLE approval_events ADD CONSTRAINT approval_events_stage_check CHECK (stage IN (
  'BROKER_REVIEW', 'EMPLOYER_VERIFICATION', 'EMPLOYER_FINANCE_VERIFICATION',
  'LENDER_INITIAL_REVIEW', 'LENDER_FINAL_REVIEW', 'DISBURSEMENT_RELEASE',
  'DISBURSEMENT_CONFIRMATION', 'REPAYMENT_WRITE_OFF', 'REPAYMENT_CONFIRMATION'
));
