-- Personal profile values are application input, not operational metadata.
-- They are stored as authenticated application ciphertext generated by the API;
-- this database never receives a plaintext fallback or a key.
ALTER TABLE users
  ADD COLUMN full_name_encrypted bytea,
  ADD COLUMN employer_name_encrypted bytea,
  ADD COLUMN personal_data_consent_version text,
  ADD COLUMN personal_data_consented_at timestamptz,
  ADD COLUMN personal_data_key_version text;

CREATE OR REPLACE FUNCTION validate_personal_profile_ciphertext_complete()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.full_name_encrypted IS NULL OR NEW.phone_encrypted IS NULL OR NEW.employer_name_encrypted IS NULL THEN
    RAISE EXCEPTION 'all personal profile fields must be encrypted together';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER users_personal_profile_ciphertext_complete
  BEFORE INSERT OR UPDATE OF full_name_encrypted, phone_encrypted, employer_name_encrypted ON users
  FOR EACH ROW
  WHEN (NEW.full_name_encrypted IS NOT NULL OR NEW.phone_encrypted IS NOT NULL OR NEW.employer_name_encrypted IS NOT NULL)
  EXECUTE FUNCTION validate_personal_profile_ciphertext_complete();
